// <auto-generated />
namespace HomeGameTracker.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class newishMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newishMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202106110240080_newishMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
