// <auto-generated />
namespace HomeGameTracker.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addingYardBoard : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingYardBoard));
        
        string IMigrationMetadata.Id
        {
            get { return "202106040207305_addingYardBoard"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
